SELECT (CASE
WHEN G.GRADE >= 8 THEN S.NAME
ELSE "NULL"
END), G.GRADE,S.MARKS FROM STUDENTS AS S 
JOIN GRADES AS G ON S.MARKS >= G.MIN_MARK AND S.MARKS<=G.MAX_MARK 
ORDER BY G.GRADE DESC,(CASE
WHEN G.GRADE >= 8 THEN S.NAME
ELSE S.MARKS
END) ASC
